# Generated by Django 3.1.1 on 2024-09-08 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
    ]
